package com.seenslide.teacher.core.report

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import com.seenslide.teacher.core.database.AttendanceEntity
import com.seenslide.teacher.core.database.StudentEntity
import java.io.File
import java.io.FileOutputStream

object ParentReportGenerator {

    private const val PAGE_WIDTH = 595 // A4 at 72 dpi
    private const val PAGE_HEIGHT = 842
    private const val MARGIN = 40f

    fun generate(
        context: Context,
        className: String,
        student: StudentEntity,
        records: List<AttendanceEntity>,
    ): File {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, 1).create()
        val page = document.startPage(pageInfo)
        val canvas = page.canvas

        val titlePaint = Paint().apply {
            color = Color.parseColor("#1B5E20")
            textSize = 22f
            isFakeBoldText = true
            isAntiAlias = true
        }
        val headingPaint = Paint().apply {
            color = Color.BLACK
            textSize = 16f
            isFakeBoldText = true
            isAntiAlias = true
        }
        val bodyPaint = Paint().apply {
            color = Color.DKGRAY
            textSize = 13f
            isAntiAlias = true
        }
        val presentPaint = Paint().apply {
            color = Color.parseColor("#2E7D32")
            textSize = 13f
            isAntiAlias = true
        }
        val absentPaint = Paint().apply {
            color = Color.parseColor("#C62828")
            textSize = 13f
            isAntiAlias = true
        }
        val linePaint = Paint().apply {
            color = Color.LTGRAY
            strokeWidth = 1f
        }

        var y = MARGIN + 30f

        // Title
        canvas.drawText("\u09AA\u09BE\u09A0\u099A\u0995\u09CD\u09B0 - Attendance Report", MARGIN, y, titlePaint)
        y += 30f

        // Divider
        canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, linePaint)
        y += 20f

        // Student info
        canvas.drawText("Student: ${student.name}", MARGIN, y, headingPaint)
        y += 22f
        if (student.rollNumber > 0) {
            canvas.drawText("Roll: ${student.rollNumber}", MARGIN, y, bodyPaint)
            y += 20f
        }
        canvas.drawText("Class: $className", MARGIN, y, bodyPaint)
        y += 30f

        // Summary
        val presentCount = records.count { it.present }
        val totalCount = records.size
        val percentage = if (totalCount > 0) (presentCount * 100) / totalCount else 0

        canvas.drawText("Attendance Summary", MARGIN, y, headingPaint)
        y += 22f
        canvas.drawText("Total Days: $totalCount", MARGIN, y, bodyPaint)
        y += 18f
        canvas.drawText("Present: $presentCount", MARGIN, y, presentPaint)
        y += 18f
        canvas.drawText("Absent: ${totalCount - presentCount}", MARGIN, y, absentPaint)
        y += 18f
        canvas.drawText("Attendance Rate: $percentage%", MARGIN, y, bodyPaint)
        y += 30f

        // Divider
        canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, linePaint)
        y += 20f

        // Daily records header
        canvas.drawText("Date", MARGIN, y, headingPaint)
        canvas.drawText("Status", PAGE_WIDTH - MARGIN - 80f, y, headingPaint)
        y += 6f
        canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, linePaint)
        y += 16f

        // Daily records
        val sortedRecords = records.sortedBy { it.date }
        for (record in sortedRecords) {
            if (y > PAGE_HEIGHT - MARGIN - 40f) {
                // Would need new page for very long lists — keep it simple, truncate
                canvas.drawText("... and more", MARGIN, y, bodyPaint)
                break
            }
            canvas.drawText(record.date, MARGIN, y, bodyPaint)
            val statusPaint = if (record.present) presentPaint else absentPaint
            val status = if (record.present) "Present" else "Absent"
            canvas.drawText(status, PAGE_WIDTH - MARGIN - 80f, y, statusPaint)
            y += 18f
        }

        // Footer
        y = PAGE_HEIGHT - MARGIN
        val footerPaint = Paint().apply {
            color = Color.GRAY
            textSize = 10f
            isAntiAlias = true
        }
        canvas.drawText("Generated by PathChakra (\u09AA\u09BE\u09A0\u099A\u0995\u09CD\u09B0)", MARGIN, y, footerPaint)

        document.finishPage(page)

        val dir = File(context.cacheDir, "reports")
        dir.mkdirs()
        val safeName = student.name.replace(Regex("[^a-zA-Z0-9\\u0980-\\u09FF]"), "_")
        val file = File(dir, "report_${safeName}.pdf")
        FileOutputStream(file).use { out ->
            document.writeTo(out)
        }
        document.close()

        return file
    }
}
